/**
 * Seed data for InvoLuck Backend
 * Sample data for development and testing purposes
 */

export const seedUsers = [
  {
    name: 'Admin User',
    email: 'admin@involuck.dev',
    password: 'AdminPassword123!',
    role: 'admin',
    isEmailVerified: true,
    preferences: {
      currency: 'USD',
      language: 'en',
      timezone: 'UTC',
      notifications: {
        email: true,
        browser: true,
        invoiceReminders: true,
        paymentReceived: true,
      },
    },
  },
  {
    name: 'John Smith',
    email: 'john@example.com',
    password: 'UserPassword123!',
    role: 'user',
    isEmailVerified: true,
    preferences: {
      currency: 'USD',
      language: 'en',
      timezone: 'America/New_York',
      notifications: {
        email: true,
        browser: false,
        invoiceReminders: true,
        paymentReceived: true,
      },
    },
  },
  {
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    password: 'UserPassword123!',
    role: 'user',
    isEmailVerified: false,
    preferences: {
      currency: 'EUR',
      language: 'en',
      timezone: 'Europe/London',
      notifications: {
        email: true,
        browser: true,
        invoiceReminders: false,
        paymentReceived: true,
      },
    },
  },
];

export const seedClients = [
  {
    name: 'Acme Corporation',
    email: 'billing@acme.com',
    company: 'Acme Corp',
    phone: '+1-555-0101',
    taxId: 'TAX-ACME-001',
    website: 'https://acme.com',
    status: 'active',
    currency: 'USD',
    paymentTerms: 30,
    billingAddress: {
      street: '123 Business Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'United States',
    },
    shippingAddress: {
      street: '123 Business Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'United States',
    },
    contactPerson: {
      name: 'Robert Brown',
      email: 'robert@acme.com',
      phone: '+1-555-0102',
      position: 'CFO',
    },
    tags: ['enterprise', 'technology'],
    notes: 'Large enterprise client with monthly retainer agreement.',
  },
  {
    name: 'Tech Startup Inc',
    email: 'finance@techstartup.io',
    company: 'Tech Startup Inc',
    phone: '+1-555-0201',
    taxId: 'TAX-TECH-002',
    website: 'https://techstartup.io',
    status: 'active',
    currency: 'USD',
    paymentTerms: 15,
    billingAddress: {
      street: '456 Innovation Drive',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
      country: 'United States',
    },
    contactPerson: {
      name: 'Lisa Wong',
      email: 'lisa@techstartup.io',
      phone: '+1-555-0202',
      position: 'Operations Manager',
    },
    tags: ['startup', 'technology', 'saas'],
    notes: 'Fast-growing startup, prefers digital invoicing.',
  },
  {
    name: 'Global Retail Ltd',
    email: 'accounts@globalretail.co.uk',
    company: 'Global Retail Ltd',
    phone: '+44-20-7946-0958',
    taxId: 'GB123456789',
    website: 'https://globalretail.co.uk',
    status: 'active',
    currency: 'GBP',
    paymentTerms: 45,
    billingAddress: {
      street: '789 Oxford Street',
      city: 'London',
      state: 'England',
      postalCode: 'W1A 0AA',
      country: 'United Kingdom',
    },
    contactPerson: {
      name: 'James Wilson',
      email: 'james@globalretail.co.uk',
      phone: '+44-20-7946-0959',
      position: 'Finance Director',
    },
    tags: ['retail', 'international'],
    notes: 'International client, requires VAT on invoices.',
  },
  {
    name: 'Local Marketing Agency',
    email: 'admin@localmarketing.com',
    company: 'Local Marketing Agency',
    phone: '+1-555-0301',
    status: 'inactive',
    currency: 'USD',
    paymentTerms: 30,
    billingAddress: {
      street: '321 Main Street',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
      country: 'United States',
    },
    contactPerson: {
      name: 'Mike Davis',
      email: 'mike@localmarketing.com',
      phone: '+1-555-0302',
      position: 'Owner',
    },
    tags: ['marketing', 'local'],
    notes: 'Client is currently on hold, may resume services next quarter.',
  },
];

export const seedInvoices = [
  {
    number: 'INV-2024-001',
    issueDate: new Date('2024-01-15'),
    dueDate: new Date('2024-02-14'),
    status: 'paid',
    currency: 'USD',
    items: [
      {
        description: 'Website Development',
        quantity: 1,
        unitPrice: 5000,
        taxRate: 8.25,
        discount: 0,
        category: 'Development',
        unit: 'project',
      },
      {
        description: 'SEO Optimization',
        quantity: 3,
        unitPrice: 500,
        taxRate: 8.25,
        discount: 10,
        category: 'Marketing',
        unit: 'hours',
      },
    ],
    taxRate: 8.25,
    discountType: 'percentage',
    discountValue: 5,
    shippingCost: 0,
    notes: 'Thank you for your business!',
    terms: 'Payment due within 30 days of invoice date.',
    tags: ['development', 'website'],
    paidAt: new Date('2024-02-10'),
  },
  {
    number: 'INV-2024-002',
    issueDate: new Date('2024-01-20'),
    dueDate: new Date('2024-02-05'),
    status: 'sent',
    currency: 'USD',
    items: [
      {
        description: 'Monthly Retainer - January 2024',
        quantity: 1,
        unitPrice: 2500,
        taxRate: 8.25,
        discount: 0,
        category: 'Consulting',
        unit: 'month',
      },
    ],
    taxRate: 8.25,
    discountType: 'fixed',
    discountValue: 0,
    shippingCost: 0,
    notes: 'Monthly retainer for ongoing consulting services.',
    terms: 'Payment due within 15 days of invoice date.',
    tags: ['retainer', 'consulting'],
    sentAt: new Date('2024-01-20'),
  },
  {
    number: 'INV-2024-003',
    issueDate: new Date('2024-01-25'),
    dueDate: new Date('2024-03-10'),
    status: 'overdue',
    currency: 'GBP',
    items: [
      {
        description: 'E-commerce Platform Setup',
        quantity: 1,
        unitPrice: 8000,
        taxRate: 20,
        discount: 0,
        category: 'Development',
        unit: 'project',
      },
      {
        description: 'Payment Gateway Integration',
        quantity: 1,
        unitPrice: 1200,
        taxRate: 20,
        discount: 0,
        category: 'Integration',
        unit: 'project',
      },
    ],
    taxRate: 20,
    discountType: 'percentage',
    discountValue: 0,
    shippingCost: 50,
    notes: 'VAT included as per UK regulations.',
    terms: 'Payment due within 45 days of invoice date.',
    tags: ['ecommerce', 'development', 'integration'],
    sentAt: new Date('2024-01-25'),
    viewedAt: new Date('2024-01-28'),
  },
  {
    number: 'INV-2024-004',
    issueDate: new Date('2024-02-01'),
    dueDate: new Date('2024-03-02'),
    status: 'draft',
    currency: 'USD',
    items: [
      {
        description: 'Mobile App Development - Phase 1',
        quantity: 1,
        unitPrice: 12000,
        taxRate: 8.25,
        discount: 0,
        category: 'Development',
        unit: 'project',
      },
      {
        description: 'UI/UX Design',
        quantity: 40,
        unitPrice: 150,
        taxRate: 8.25,
        discount: 5,
        category: 'Design',
        unit: 'hours',
      },
    ],
    taxRate: 8.25,
    discountType: 'percentage',
    discountValue: 3,
    shippingCost: 0,
    notes: 'Draft invoice for mobile app development project.',
    terms: 'Payment due within 30 days of invoice date.',
    tags: ['mobile', 'development', 'design'],
  },
];

export default {
  seedUsers,
  seedClients,
  seedInvoices,
};
